name: Scheduled Nightly GPU Tests

on:
  push:
    branches:
      - ershi/test-nightly-gpu

jobs:
  gpu-tests:
    if: github.repository == 'shi-eric/newton'
    uses: ./.github/workflows/aws_gpu_tests.yml
    with:
      instance-type: g7e.12xlarge  # 2x NVIDIA RTX PRO 6000, 48 vCPUs
      volume-size: '92'
    permissions:
      id-token: write
      contents: read
    secrets: inherit
